.ORIG x3000

; set the ISR
LEA R0, KB_ISR
STI R0, KBIV
LEA R0, TIMER_ISR
STI R0, TMIV
LD R0, TIMEOUT
STI R0, TMDR
; set interrupt enable
LD R0, INTERRUPT_ENABLE
STI R0, KBSR
STI R0, TMSR
BRnzp #-1

TIMER_ISR
ST R0, TIMER_ISR_SAVE_R0
LD R0, TIMEOUT
STI R0, TMDR
LDI R0, DSR
BRzp #-2
LD R0, MYSTRING
STI R0, DDR
LD R0, TIMER_ISR_SAVE_R0
RTI
TIMER_ISR_SAVE_R0 .FILL #0  

KB_ISR
  ST R0, KB_ISR_SAVE_R0
  ST R1, KB_ISR_SAVE_R1
  LDI R0, KBDR
KB_ISR_DISPLAY_WAIT
  LDI R1, DSR
  BRzp KB_ISR_DISPLAY_WAIT
  STI R0, DDR
  LD R0, KB_ISR_SAVE_R0
  LD R1, KB_ISR_SAVE_R1
  RTI
KB_ISR_SAVE_R0 .FILL #0
KB_ISR_SAVE_R1 .FILL #0

MYSTRING .STRINGZ "."
KBSR .FILL xFE00
KBDR .FILL xFE02
DSR  .FILL xFE04
DDR  .FILL xFE06
TMSR .FILL xFE08
TMDR .FILL xFE0A
TIMEOUT .FILL #100
KBIV .FILL x0180
TMIV .FILL x0182
INTERRUPT_ENABLE .FILL x4000

.END