.ORIG x3000

LEA R1, TEST_STRING
LD R6, STACK_START

PUSH_LOOP
    LDR R0, R1, #0
    BRz PUSH_END
    ADD R6, R6, #-1 ; push
    STR R0, R6, #0  ;;
    ADD R1, R1, #1
    BRnzp PUSH_LOOP

PUSH_END
    LEA R1, TEST_STRING

POP_LOOP
    LDR R0, R1, #0
    BRz POP_END
    NOT R0, R0
    ADD R0, R0, #1
    LDR R2, R6, #0 ; pop
    ADD R6, R6, #1 ;;
    ADD R0, R0, R2
    BRnp NOT_A_PALINDROME
    ADD R1, R1, #1
    BRnzp POP_LOOP

POP_END
    LEA R0, TEST_STRING
    PUTS
    LEA R0, IS_PALINDROME_STRING
    PUTS
    HALT

NOT_A_PALINDROME
    LEA R0, NOT_PALINDROME_STRING
    PUTS
    HALT

TEST_STRING .STRINGZ "palindrome"
STACK_START .FILL x4000
NOT_PALINDROME_STRING .STRINGZ "Not a palindrome"
IS_PALINDROME_STRING .STRINGZ " is a palindrome"

.END